### ISSUE TITLE
we could never step into this if-statement 

### ISSUE THREAD

**Issue by busyyang** [CPSC-Committee/cpsc2021#2]
Hi Committee,

In Line 143 of `score_2021.py`, there is a if statement, `np.diff(endpoints_pred)[-1] == TrueRef.len_sig`, may be a wrong condition. 
~~~py
......
elif len(endpoints_pred) == 1 and np.diff(endpoints_pred)[-1] == TrueRef.len_sig:
    class_pred = 2
......
~~~

There is an example. If the length of input array is 10000, and we make a prediction result `{"predict_endpoints": [[0, 9999]]}`. The prediction result should be persistent AF rhythm with `class_pred = 2`. But as we known, the index of array start with 0 and end with the `length-1` in python,  the result of `np.diff(endpoints_pred)[-1]` will be 9999 which is not suit the length of array, even we make a right prediction.

When we make a breakpointer for `class_pred = 2` and  run code on debug mode. It will never stop there even we absolutely make some right prediction.

For this part, we think is could be the code as below:
~~~py
......
elif len(endpoints_pred) == 1 and np.diff(endpoints_pred)[-1] == TrueRef.len_sig - 1:
    class_pred = 2
......
~~~

**Comment by cpsc-helper** [comment]
> Hi Committee,
> 
> In Line 143 of `score_2021.py`, there is a if statement, `np.diff(endpoints_pred)[-1] == TrueRef.len_sig`, may be a wrong condition.
> 
> ```python
> ......
> elif len(endpoints_pred) == 1 and np.diff(endpoints_pred)[-1] == TrueRef.len_sig:
>     class_pred = 2
> ......
> ```
> 
> There is an example. If the length of input array is 10000, and we make a prediction result `{"predict_endpoints": [[0, 9999]]}`. The prediction result should be persistent AF rhythm with `class_pred = 2`. But as we known, the index of array start with 0 and end with the `length-1` in python, the result of `np.diff(endpoints_pred)[-1]` will be 9999 which is not suit the length of array, even we make a right prediction.
> 
> When we make a breakpointer for `class_pred = 2` and run code on debug mode. It will never stop there even we absolutely make some right prediction.
> 
> For this part, we think is could be the code as below:
> 
> ```python
> ......
> elif len(endpoints_pred) == 1 and np.diff(endpoints_pred)[-1] == TrueRef.len_sig - 1:
>     class_pred = 2
> ......
> ```

Thank you for the report! We have fixed the condition.
